name: Deploy to Amazon Linux EC2

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.100-rc.2.24474.11"

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Publish .NET Core app
        run: dotnet publish src/Minigun/Minigun.csproj -c Release -r linux-x64 --self-contained -o ./publish

      - name: Upload files to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          DEPLOY_DIR: /var/www/minigun
        run: |
          echo "$EC2_SSH_KEY" > ./ec2_key.pem
          chmod 600 ./ec2_key.pem

          # Add SSH config to disable strict host key checking
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" > ~/.ssh/config

          # Test SSH connection first
          ssh -i ./ec2_key.pem -v $EC2_USER@$EC2_HOST "echo 'SSH connection successful'"

          # Create directory if it doesn't exist
          ssh -i ./ec2_key.pem $EC2_USER@$EC2_HOST "sudo mkdir -p $DEPLOY_DIR && sudo chown -R $EC2_USER:$EC2_USER $DEPLOY_DIR"

          # Upload the files to EC2 with verbose output
          scp -i ./ec2_key.pem -r -v ./publish/* $EC2_USER@$EC2_HOST:$DEPLOY_DIR

      - name: Restart Application on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          DEPLOY_DIR: /var/www/minigun
        run: |
          ssh -i ./ec2_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            # Stop any existing instance
            pkill -f "minigun" || true

            # Navigate to the deployment directory and start the app
            cd $DEPLOY_DIR
            nohup ./minigun > /dev/null 2>&1 &
          EOF

      - name: Clean up
        run: rm -f ./ec2_key.pem
